theme: jekyll-theme-cayman
title: Deep Learning for One-dimensional Consolidation
description: Physics-Informed Neural Networks in Soil Mechanics
markdown: kramdown
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge